//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERealtyDatabases.Databases.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IERealtyDbContext : DbContext
    {
        public IERealtyDbContext()
            : base("name=IERealtyDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblAddress> tblAddresses { get; set; }
        public DbSet<tblAgent> tblAgents { get; set; }
        public DbSet<tblAgentAvaialbleForAppointment> tblAgentAvaialbleForAppointments { get; set; }
        public DbSet<tblBroker> tblBrokers { get; set; }
        public DbSet<tblBrokerAgent> tblBrokerAgents { get; set; }
        public DbSet<tblCustomerAppointment> tblCustomerAppointments { get; set; }
    }
}
