//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERealtyDatabases.Databases.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAppointment
    {
        public long Id { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public long DurationInMinutes { get; set; }
        public string Message { get; set; }
        public long AvailableAgentId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblAgentAvaialbleForAppointment tblAgentAvaialbleForAppointment { get; set; }
    }
}
